spring.application.name=eureka-server

# configure server port
server.port=8761

# info app
info.app.name=eureka-server
info.app.description=eureka server responsible for managing service discovery
info.app.version=1.0

spring.main.banner-mode=off
logging.level.root=info

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


